node {
    def app

    stage('Clone repository') {
        checkout scm
    }

    stage('Build image') {
        app = docker.build("yogstation/yogbot")
    }

    stage('Push image') {
        docker.withRegistry('https://registry.hub.docker.com', 'yogstation-docker-hub-credentials') {
            app.push("${env.BUILD_NUMBER}")
            app.push("latest")
        }
    }

    stage('Deploy') {
        kubernetesDeploy(kubeconfigId: 'yogstation-kubernetes-credentials',

                 configs: '.jenkins/deploy.yml',
                 enableConfigSubstitution: true
        )       
    }
}